#!/bin/bash

_script="$(readlink -f ${BASH_SOURCE[0]})"
_base="$(dirname $_script)"

if [ -z $1 ]; then
	echo "Usage <command> [options]"
	echo "Available commands:"
	echo "	conc:	calculate the concordance between sampels in a cohort"
	echo "	heat:	print a heat map of results"
	echo "	model:	create a model for the cohort concordance values and establish relationships"
	exit
elif [ $1 = "conc" ]; then
	shift 
	${_base}/concordance_script.py $@ 
elif [ $1 = "heat" ]; then
	if [ -z $3 ]; then
		echo "Usage for the heat map command: <input file (as generated by conc)> <output pdf>"
		exit
	fi
	shift
	R --no-save --args $1 $2 < ${_base}/plotting_script.R 
elif [ $1 = "model" ]; then
	shift
	${_base}/model_analysis.py $@
else
	echo "Unknown command: ${1}. Exiting"
fi
